### ISSUE TITLE
XAML Preview button does not showing the 👁️ image

### ISSUE THREAD

**Issue by microhobby** [microhobby/vs-code-uno-platform#3]
XAML preview button appears to have wrong path or something else, the button are show all white

**Comment by microhobby** [comment]
8268ee460384c3811c038399c54dcf97084fecd0 fixed

**Comment by Red-Ex** [comment]
Hello microhobby,

unfortunately I have that problem on one of my machines. Is there a possibility for debugging/logging? The current state is that the preview loads to nearly 90%. After that the splash screen appears for some seconds and at the end the preview window is black(empty).

Thank you😊!
